"""add is_read to contact_messages

Revision ID: 2faa170a3354
Revises: cfe5bef7831d
Create Date: 2026-07-11 19:16:15.100723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2faa170a3354'
down_revision: Union[str, None] = 'cfe5bef7831d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_messages', 'is_read')
    # ### end Alembic commands ###
