"""align contact_messages.created_at model with timezone-aware column

Revision ID: a106dc678faa
Revises: 2ab9a8a5b57b
Create Date: 2026-07-10 23:22:13.477193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a106dc678faa'
down_revision: Union[str, None] = '2ab9a8a5b57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
