"""add extra_specs to estimates

Revision ID: aa1916f478a3
Revises: 2faa170a3354
Create Date: 2026-07-12 21:18:41.845567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aa1916f478a3'
down_revision: Union[str, None] = '2faa170a3354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estimates', sa.Column('extra_specs', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estimates', 'extra_specs')
    # ### end Alembic commands ###
